@echo off
echo Fixing corrupted Next.js SWC binary...
if exist "node_modules\@next\swc-win32-x64-msvc" (
    echo Removing corrupted SWC folder...
    rmdir /s /q "node_modules\@next\swc-win32-x64-msvc"
)
if exist ".next" (
    echo Cleaning .next cache...
    rmdir /s /q ".next"
)
echo Re-running dev server...
npm run dev
